###
GET http://localhost:3000/

###
GET http://localhost:3000/health



### CREATE TODO
POST http://localhost:3000/todo
Content-Type: application/json

{
    "title": "Computador Mackintosh123",
    "content": "Criar um Mackintosh123",
    "category": "Computador"
}


### LIST TODO
GET http://localhost:3000/todos
Content-Type: application/json


### Define variable
@id=33c8746d-ccb0-437b-a9e8-868b69c1fa47

### GET TODO
GET http://localhost:3000/todo/{{id}}
Content-Type: application/json



#### patch
PATCH http://localhost:3000/todo/{{id}}
Content-Type: application/json

{
    "title": "Jogos - GE Force Now22",
    "content": "comprar GE Force jogar no macos",
    "category": "Jogos PC"
}


### DELETE TODO
DELETE http://localhost:3000/todo/{{id}}
Content-Type: application/json